### ISSUE TITLE
Reference materials

### ISSUE THREAD

**Issue by brandondrew** [nhajratw/minecraft_api#2]
Hi, I don't see any examples, or links to an API reference.  Perhaps this is obvious to someone who has used a different API (Python? Java? Scratch?) for Minecraft, but if you could provide a starting point, that would be very useful.  Included examples would be even better.  Thanks!

**Comment by brandondrew** [comment]
Can you mention in the README how I find what server I'm connecting to?   (I'm sure I'm not the only one who will need to know.)  Thanks!

**Comment by brandondrew** [comment]
By the way, thanks for the info!

**Comment by nhajratw** [comment]
are you saying you'd like information on how to figure out the hostname/ip address of the server you installed minecraft on?

**Comment by brandondrew** [comment]
No, if I'd installed it on a server I'd know that.  

I have a Pi that my kids play Minecraft on.  Whatever server we're using (if any--is there always a server involved?  Or do you by default play locally? I think there's always a server since they've told me that their friends have visited their worlds) is just whatever is set up by default.  I don't personally play Minecraft, and I know almost nothing about it.  But I see it as an opportunity to interest my kids in learning Ruby, which would otherwise seem quite abstruse and useless to them.  I only let them play Minecraft if they programmatically change their worlds (with the Scratch interface that comes with the Pi's version of Minecraft).  But I'd rather have them use Ruby, and I'm pretty sure they'd eventually find it easier and faster.

I'm sure I could figure this out with some Googling (and probably asking my kids to explain some things about the game), but it seems like the sort of information that would be useful to have here in the README, since (as far as I understand) this project is all about helping people use Ruby in Minecraft, and that info would help make it easier for more people to get started with that.

**Comment by nhajratw** [comment]
I'm still not sure i understand what you're asking for.

If you install Minecraft for RPI on server 192.168.1.100, then you would use that IP address when using the API...

If you're running the api locally on the same RPI that you're running minecraft, then you can use the IP address or just say 'localhost'.

I feel like i'm missing something from your question though, so maybe try to explain specifically what you're trying to do, and where you're getting stuck.

Thanks!

**Comment by nhajratw** [comment]
closed due to inactivity ... feel free to open a new one with a specific request.
